algoritmo "soma"
var
  n1, n2, soma: Inteiro
inicio
  escreval("Calculadora: Soma de 2 numeros")
  escreval("Usando VisuAlg")
  escreval("")
  escreva("Informe um numero: ")
  leia(n1)
  escreva("Informe outro numero: ")
  leia(n2)
  soma <- n1 + n2
  escreval("")
  escreval("Calculando o resultado...")
  escreval("")
  escreval("A soma de", n1, " com", n2, " eh igual a", soma, ".")
  escreval("")
fimalgoritmo
